# .env === application.yml

MYSQL_ROOT_PASSWORD: 123456

MYSQL_ROOT_USER: root

MYSQL_DATABASE: sgdbd

PORT_BACK: 807

DATABASE_URL: jdbc:mysql://localhost:3306/sgdbd?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=America/Santiago&verifyServerCertificate=false&useSSL=true&requireSSL=false
